name: Feature request
description: Propose an idea or improvement
title: "feat: "
labels: [enhancement]
body:
  - type: textarea
    id: proposal
    attributes:
      label: Proposal
    validations:
      required: true
