name: Question
description: Ask a question
title: "question: "
labels: [question]
body:
  - type: textarea
    id: question
    attributes:
      label: Question
    validations:
      required: true
